import { Link } from 'react-router-dom';
import { Card } from '../../components/Common/Card';
import { useShipments } from '../../hooks/useDashboardQueries';

export function LogisticsDashboard() {
  const { data, isLoading, isError } = useShipments({ page_size: 50 });
  const batches = data?.results ?? [];
  const count = (status: string) => batches.filter((batch) => batch.status === status).length;
  return <div className="space-y-6" data-role="logistics"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-cyan-400">Custody workspace</p><h1 className="text-3xl font-bold text-fg-primary">Logistics dashboard</h1><p className="mt-1 text-sm text-fg-muted">Track produce currently in your custody and record verified handoffs.</p></div><Link className="rounded-xl bg-cyan-500 px-4 py-2.5 text-sm font-semibold text-slate-950 hover:bg-cyan-400" to="/logistics/transfer">Transfer custody</Link></div><div className="grid gap-4 sm:grid-cols-3"><Card variant="glass" padding="md"><p className="text-xs uppercase text-fg-muted">Visible batches</p><p className="mt-2 text-3xl font-bold text-fg-primary">{data?.count ?? 0}</p></Card><Card variant="glass" padding="md"><p className="text-xs uppercase text-fg-muted">In transit</p><p className="mt-2 text-3xl font-bold text-cyan-400">{count('IN_TRANSIT')}</p></Card><Card variant="glass" padding="md"><p className="text-xs uppercase text-fg-muted">Delivered</p><p className="mt-2 text-3xl font-bold text-emerald-400">{count('DELIVERED')}</p></Card></div><Card variant="glass" padding="md"><div className="mb-4"><h2 className="text-lg font-semibold text-fg-primary">Custody batches</h2><p className="text-sm text-fg-muted">Only batches you created or currently hold are shown.</p></div>{isLoading && <p className="py-10 text-center text-fg-muted">Loading custody records…</p>}{isError && <p className="py-10 text-center text-red-400">Custody records could not be loaded.</p>}<div className="space-y-2">{batches.map((batch) => <div key={batch.id} className="grid gap-3 rounded-xl border border-border-primary/60 bg-bg-tertiary/40 p-4 sm:grid-cols-[1fr_auto_auto] sm:items-center"><div><p className="font-medium text-fg-primary">{batch.crop_type} · {batch.weight_kg} kg</p><p className="font-mono text-xs text-fg-muted">{batch.id}</p></div><span className="text-xs font-semibold text-cyan-400">{batch.status.replace('_', ' ')}</span><Link className="text-sm font-medium text-fg-primary hover:text-cyan-400" to={`/logistics/transfer?batch=${batch.id}`}>Handoff →</Link></div>)}{!isLoading && batches.length === 0 && <p className="py-10 text-center text-fg-muted">No produce batches are currently assigned to this account.</p>}</div></Card></div>;
}
