# Generated by Django 6.0.8 on 2026-09-01 02:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("AUTH_SUCCESS", "Authentication Success"),
                            ("AUTH_FAILURE", "Authentication Failure"),
                            ("SECURITY_ALERT", "Security Alert / GCM Tag Mismatch"),
                            ("INTEGRITY_CHECK_PASS", "Integrity Audit Pass"),
                            ("INTEGRITY_CHECK_FAIL", "Integrity Audit Failure"),
                            ("BATCH_PREPARE", "Batch Prepared"),
                            ("BATCH_CONFIRM", "Batch Mint Confirmed"),
                            ("CUSTODY_TRANSFER", "Custody Transferred"),
                            ("ADMIN_ACTION", "Administrative Action"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "wallet_address",
                    models.CharField(blank=True, default="", max_length=66),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("description", models.TextField()),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "timestamp"],
                        name="users_audit_event_t_395278_idx",
                    ),
                    models.Index(
                        fields=["user", "timestamp"],
                        name="users_audit_user_id_84b6be_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WalletChallenge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("wallet_address", models.CharField(db_index=True, max_length=66)),
                ("nonce", models.CharField(max_length=64, unique=True)),
                ("domain", models.CharField(default="TerraNode Auth", max_length=100)),
                ("message", models.TextField()),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="challenges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-issued_at"],
                "indexes": [
                    models.Index(
                        fields=["wallet_address", "expires_at"],
                        name="users_walle_wallet__3f2aa5_idx",
                    )
                ],
            },
        ),
    ]
