# Generated by Django 5.2.15 on 2026-06-27 03:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='environmentaltelemetry',
            name='recorded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddIndex(
            model_name='environmentaltelemetry',
            index=models.Index(fields=['farmer', 'recorded_at'], name='telemetry_e_farmer__ea2b8c_idx'),
        ),
    ]
