# Generated by Django 5.2.15 on 2026-06-27 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0002_alter_environmentaltelemetry_recorded_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environmentaltelemetry',
            name='recorded_at',
            field=models.DateTimeField(),
        ),
    ]
