# Generated by Django 6.0.8 on 2026-09-01 02:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("telemetry", "0003_alter_environmentaltelemetry_recorded_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataProvenance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Manual Observation"),
                            ("DATASET_IMPORT", "External Dataset Import"),
                            ("SENSOR", "Hardware Sensor"),
                            ("SYNTHETIC", "Synthetic / Demo Data"),
                        ],
                        default="MANUAL",
                        max_length=30,
                    ),
                ),
                (
                    "provider_name",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                (
                    "dataset_name",
                    models.CharField(blank=True, default="", max_length=150),
                ),
                ("source_url", models.URLField(blank=True, default="", max_length=500)),
                (
                    "source_record_id",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("license_attribution", models.TextField(blank=True, default="")),
                ("retrieval_timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "raw_payload_sha256",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("time_standard", models.CharField(default="UTC", max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name="environmentaltelemetry",
            name="auth_tag_b64",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="environmentaltelemetry",
            name="encrypted_payload_b64",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="environmentaltelemetry",
            name="key_version",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="environmentaltelemetry",
            name="nonce_b64",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="environmentaltelemetry",
            name="schema_version",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="environmentaltelemetry",
            name="soil_moisture_percentage",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="environmentaltelemetry",
            name="soil_ph",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="environmentaltelemetry",
            name="temperature_celsius",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="environmentaltelemetry",
            name="provenance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="telemetry_records",
                to="telemetry.dataprovenance",
            ),
        ),
        migrations.CreateModel(
            name="ImportRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Success"),
                            ("PARTIAL", "Partial Import"),
                            ("FAILED", "Failed"),
                        ],
                        default="SUCCESS",
                        max_length=20,
                    ),
                ),
                ("records_inserted", models.IntegerField(default=0)),
                ("records_skipped", models.IntegerField(default=0)),
                ("records_failed", models.IntegerField(default=0)),
                ("validation_errors", models.JSONField(blank=True, default=list)),
                (
                    "provenance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_runs",
                        to="telemetry.dataprovenance",
                    ),
                ),
            ],
        ),
    ]
