# Generated by Django 5.2.17 on 2026-08-22 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='producebatch',
            new_name='ledger_prod_status_ba6a07_idx',
            old_name='ledger_batch_status_idx',
        ),
        migrations.RenameIndex(
            model_name='producebatch',
            new_name='ledger_prod_farmer__07a5b7_idx',
            old_name='ledger_batch_farmer_idx',
        ),
    ]
