# Generated by Django 6.0.8 on 2026-09-01 02:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ledger",
            "0002_rename_ledger_batch_status_idx_ledger_prod_status_ba6a07_idx_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustodyTransfer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "from_wallet",
                    models.CharField(blank=True, default="", max_length=66),
                ),
                ("to_wallet", models.CharField(blank=True, default="", max_length=66)),
                ("tx_digest", models.CharField(blank=True, default="", max_length=66)),
                ("verified_on_chain", models.BooleanField(default=False)),
                ("transferred_at", models.DateTimeField(auto_now_add=True)),
                ("event_metadata", models.JSONField(blank=True, default=dict)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers",
                        to="ledger.producebatch",
                    ),
                ),
                (
                    "from_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="transfers_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="transfers_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-transferred_at"],
                "indexes": [
                    models.Index(
                        fields=["batch", "transferred_at"],
                        name="ledger_cust_batch_i_234631_idx",
                    )
                ],
            },
        ),
    ]
