import hashlib
import json


CURRENT_SCHEMA_VERSION = 1
LEGACY_SCHEMA_VERSION = 0


def canonical_telemetry_payload(
    farmer_id,
    recorded_at,
    temperature,
    soil_moisture,
    soil_ph,
    schema_version=CURRENT_SCHEMA_VERSION,
):
    """Return the canonical, versioned bytes hashed and encrypted by TerraNode."""
    recorded_at_iso = recorded_at if isinstance(recorded_at, str) else recorded_at.isoformat()
    payload = {
        "farmer_id": str(farmer_id),
        "recorded_at": recorded_at_iso,
        "temperature_celsius": f"{temperature:.2f}" if temperature is not None else None,
        "soil_moisture_percentage": f"{soil_moisture:.2f}" if soil_moisture is not None else None,
        "soil_ph": f"{soil_ph:.2f}" if soil_ph is not None else None,
    }
    # Version zero exactly preserves hashes generated by the original implementation.
    if schema_version != LEGACY_SCHEMA_VERSION:
        payload["schema_version"] = schema_version
    return json.dumps(payload, sort_keys=True, separators=(",", ":")).encode("utf-8")


def generate_telemetry_hash(
    farmer_id,
    recorded_at,
    temperature,
    soil_moisture,
    soil_ph,
    schema_version=CURRENT_SCHEMA_VERSION,
):
    return hashlib.sha256(
        canonical_telemetry_payload(
            farmer_id,
            recorded_at,
            temperature,
            soil_moisture,
            soil_ph,
            schema_version=schema_version,
        )
    ).hexdigest()
