import { Link } from 'react-router-dom';
import { Card } from '../../components/Common/Card';
import { useAdminStats, useAuditLogs, useSystemHealth } from '../../hooks/useDashboardQueries';

export function AdminDashboard() {
  const stats = useAdminStats(); const health = useSystemHealth(); const audit = useAuditLogs({ page_size: 6 });
  const values = stats.data;
  return <div className="space-y-6" data-role="admin"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-violet-400">System oversight</p><h1 className="text-3xl font-bold text-fg-primary">Administrator dashboard</h1><p className="mt-1 text-sm text-fg-muted">Users, ledger activity, integrity events, and service health from live APIs.</p></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[['Users', values?.total_users ?? 0],['Telemetry records', values?.telemetry_records ?? 0],['Produce batches', values?.total_batches ?? 0],['Integrity flags', values?.flagged_anomalies ?? 0]].map(([label,value]) => <Card key={label} variant="glass" padding="md"><p className="text-xs uppercase text-fg-muted">{label}</p><p className="mt-2 text-3xl font-bold text-fg-primary">{value}</p></Card>)}</div><div className="grid gap-6 lg:grid-cols-2"><Card variant="glass" padding="md"><div className="mb-4 flex items-center justify-between"><h2 className="text-lg font-semibold text-fg-primary">Service health</h2><Link className="text-sm text-violet-400" to="/admin/system-health">Details</Link></div><div className="space-y-2">{Object.entries(health.data ?? {}).map(([name,status]) => <div key={name} className="flex justify-between rounded-xl bg-bg-tertiary/40 p-3"><span className="capitalize text-fg-secondary">{name}</span><span className={status === 'healthy' ? 'text-emerald-400' : 'text-amber-400'}>{String(status).replace('_',' ')}</span></div>)}</div></Card><Card variant="glass" padding="md"><div className="mb-4 flex items-center justify-between"><h2 className="text-lg font-semibold text-fg-primary">Recent audit events</h2><Link className="text-sm text-violet-400" to="/admin/audit-logs">Full trail</Link></div><div className="space-y-2">{(audit.data?.results ?? []).slice(0,6).map((event) => <div key={event.id} className="rounded-xl bg-bg-tertiary/40 p-3"><div className="flex justify-between gap-3"><span className="text-xs font-semibold text-violet-400">{event.action.replaceAll('_',' ')}</span><span className="text-xs text-fg-muted">{new Date(event.timestamp).toLocaleString()}</span></div><p className="mt-1 text-sm text-fg-secondary">{event.description}</p></div>)}</div></Card></div></div>;
}
