import { useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { Card } from '../../components/Common/Card';
import { useBatches } from '../../hooks/useDashboardQueries';
import type { BatchStatus } from '../../types/ledger';

export function BatchesPage() {
  const [search, setSearch] = useState('');
  const [status, setStatus] = useState<'ALL' | BatchStatus>('ALL');
  const { data, isLoading, isError } = useBatches({ page_size: 100 });
  const rows = useMemo(() => (data?.results ?? []).filter((batch) => (status === 'ALL' || batch.status === status) && `${batch.id} ${batch.crop_type}`.toLowerCase().includes(search.toLowerCase())), [data, search, status]);
  return <div className="space-y-6" data-role="farmer"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-emerald-400">Produce ledger</p><h1 className="text-3xl font-bold text-fg-primary">My batches</h1><p className="mt-1 text-sm text-fg-muted">Track each batch through the thesis lifecycle: pending, minted, in transit, delivered.</p></div><Link className="rounded-xl bg-emerald-500 px-4 py-2.5 text-sm font-semibold text-slate-950" to="/farmer/mint-batch">Create batch</Link></div><Card variant="glass" padding="md"><div className="mb-5 flex flex-col gap-3 sm:flex-row"><input className="min-h-11 flex-1 rounded-xl border border-border-primary bg-bg-tertiary px-4 text-fg-primary outline-none focus:border-emerald-500" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search crop or batch ID" /><select className="min-h-11 rounded-xl border border-border-primary bg-bg-tertiary px-4 text-fg-primary" value={status} onChange={(event) => setStatus(event.target.value as 'ALL' | BatchStatus)}><option value="ALL">All statuses</option><option value="PENDING">Pending</option><option value="MINTED">Minted</option><option value="IN_TRANSIT">In transit</option><option value="DELIVERED">Delivered</option></select></div>{isLoading && <p className="py-10 text-center text-fg-muted">Loading batches…</p>}{isError && <p className="py-10 text-center text-red-400">Batches could not be loaded.</p>}<div className="space-y-3">{rows.map((batch) => <article key={batch.id} className="grid gap-3 rounded-xl border border-border-primary/60 bg-bg-tertiary/40 p-4 md:grid-cols-[1.2fr_.5fr_.5fr_1fr] md:items-center"><div><p className="font-semibold text-fg-primary">{batch.crop_type}</p><p className="font-mono text-xs text-fg-muted">{batch.id}</p></div><div><p className="text-xs uppercase text-fg-muted">Weight</p><p className="text-sm text-fg-primary">{batch.weight_kg} kg</p></div><div><p className="text-xs uppercase text-fg-muted">Status</p><p className="text-sm font-semibold text-emerald-400">{batch.status.replace('_', ' ')}</p></div><div className="min-w-0"><p className="text-xs uppercase text-fg-muted">Sui object</p><p className="truncate font-mono text-xs text-fg-secondary">{batch.sui_object_id || 'Awaiting mint confirmation'}</p></div></article>)}{!isLoading && rows.length === 0 && <p className="py-12 text-center text-fg-muted">No batches match the current filters.</p>}</div></Card></div>;
}
