import { Link } from 'react-router-dom';
import { Card } from '../../components/Common/Card';
import { useBatches, useLatestTelemetry, useYieldPrediction } from '../../hooks/useDashboardQueries';

const metric = (label: string, value: string, note: string) => <Card variant="glass" padding="md"><p className="text-xs font-semibold uppercase tracking-wider text-fg-muted">{label}</p><p className="mt-2 text-3xl font-bold text-fg-primary">{value}</p><p className="mt-1 text-xs text-fg-muted">{note}</p></Card>;

export function FarmerDashboard() {
  const telemetry = useLatestTelemetry();
  const batches = useBatches({ page_size: 5 });
  const prediction = useYieldPrediction();
  const latest = telemetry.data;
  return <div className="space-y-6" data-role="farmer">
    <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-emerald-400">Farm overview</p><h1 className="text-3xl font-bold text-fg-primary">Your agricultural record</h1><p className="mt-1 text-sm text-fg-muted">Live telemetry, blockchain batches, and the thesis yield model in one place.</p></div><div className="flex gap-2"><Link className="rounded-xl border border-border-primary px-4 py-2.5 text-sm text-fg-primary hover:border-emerald-500" to="/farmer/telemetry">Add reading</Link><Link className="rounded-xl bg-emerald-500 px-4 py-2.5 text-sm font-semibold text-slate-950 hover:bg-emerald-400" to="/farmer/mint-batch">Create batch</Link></div></div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metric('Temperature', latest?.temperature_celsius == null ? '—' : `${latest.temperature_celsius.toFixed(1)}°C`, latest?.recorded_at ? `Recorded ${new Date(latest.recorded_at).toLocaleString()}` : 'No readings yet')}{metric('Soil moisture', latest?.soil_moisture_percentage == null ? '—' : `${latest.soil_moisture_percentage.toFixed(1)}%`, 'Validated range: 0–100%')}{metric('Soil pH', latest?.soil_ph == null ? '—' : latest.soil_ph.toFixed(1), 'Validated range: 0–14')}{metric('Produce batches', String(batches.data?.count ?? 0), 'Across the full custody lifecycle')}</div>
    <div className="grid gap-6 lg:grid-cols-[1.2fr_.8fr]"><Card variant="glass" padding="md"><div className="mb-4 flex items-center justify-between"><div><h2 className="text-lg font-semibold text-fg-primary">Recent batches</h2><p className="text-sm text-fg-muted">Database and Sui ledger state</p></div><Link className="text-sm font-medium text-emerald-400" to="/farmer/batches">View all</Link></div>{batches.isLoading ? <p className="py-10 text-center text-fg-muted">Loading batches…</p> : <div className="space-y-2">{(batches.data?.results ?? []).map((batch) => <div key={batch.id} className="flex items-center justify-between rounded-xl border border-border-primary/60 bg-bg-tertiary/40 p-3"><div><p className="font-medium text-fg-primary">{batch.crop_type}</p><p className="font-mono text-xs text-fg-muted">{batch.id.slice(0, 12)}… · {batch.weight_kg} kg</p></div><span className="rounded-full bg-emerald-500/10 px-2.5 py-1 text-xs font-semibold text-emerald-400">{batch.status.replace('_', ' ')}</span></div>)}{batches.data?.results.length === 0 && <p className="py-10 text-center text-fg-muted">No batches yet. Create your first verified produce batch.</p>}</div>}</Card><Card variant="glass" padding="md"><h2 className="text-lg font-semibold text-fg-primary">Yield forecast</h2>{prediction.isSuccess ? <><p className="mt-5 text-4xl font-bold text-fg-primary">{prediction.data.predicted_yield_metric_tons.toFixed(2)} <span className="text-base font-normal text-fg-muted">metric tons</span></p><p className="mt-2 text-sm text-fg-muted">Confidence {(prediction.data.confidence_score * 100).toFixed(0)}% from {prediction.data.data_points_analyzed} readings</p><div className="mt-5 rounded-xl border border-emerald-500/20 bg-emerald-500/10 p-4 text-sm text-emerald-200">{prediction.data.recommendation}</div></> : <><p className="mt-5 text-sm text-fg-muted">At least five telemetry readings are required before a forecast can be computed.</p><Link className="mt-4 inline-block text-sm font-semibold text-emerald-400" to="/farmer/telemetry">Record telemetry →</Link></>}</Card></div>
  </div>;
}
